name: vocab_crammer
description: A vocabulary learning app for Hebrew and Greek.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hebrew.txt
    - assets/greek.txt

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cram-icon.jpg"
