name: vocab_crammer
description: A vocabulary learning app for Greek and Hebrew words
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  awesome_notifications: ^0.9.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/greek_vocabulary.json
    - assets/hebrew_vocabulary.json
